services:
  mysql:
    container_name: 'magalu-mysql'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=magalu_db'
      - 'MYSQL_PASSWORD=123'
      - 'MYSQL_ROOT_PASSWORD=123'
      - 'MYSQL_USER=admin'
    ports:
      - '3306:3306'